### ISSUE TITLE
Caused by: java.util.MissingResourceException: Can't find bundle for base name resources.AstrosoftBundle, locale en

### ISSUE THREAD

**Issue by rajeshzmoke** [erajasekar/Astrosoft#1]
i get `Exception in thread "main" java.lang.ExceptionInInitializerError
	at app.astrosoft.consts.Planet.toString(Planet.java:341)
	at app.astrosoft.core.VimDasa.fullDasa(VimDasa.java:93)
	at app.astrosoft.core.VimDasa.getColumnData(VimDasa.java:220)
	at app.astrosoft.ui.table.TableDataFactory.toCSV(TableDataFactory.java:79)
	at app.astrosoft.core.Vimshottari.main(Vimshottari.java:237)
Caused by: java.util.MissingResourceException: Can't find bundle for base name resources.AstrosoftBundle, locale en
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at app.astrosoft.util.Internalization.loadBundles(Internalization.java:68)
	at app.astrosoft.util.Internalization.<clinit>(Internalization.java:48)
	... 5 more`  when trying to run Vimshottari.java

**Comment by erajasekar** [comment]
Are you not running it with included shell or batch file? How are you running it?

**Comment by rajeshzmoke** [comment]
running the shell file works...but i was trying to get the output in the console , how can i achieve this?

**Comment by erajasekar** [comment]
Just run the command in shell script in your terminal like `java -Djava.util.logging.config.file=./logging.properties -Djava.util.prefs.PreferencesFactory=app.astrosoft.pref.UserPreferencesFactory -jar bin/AstroSoft.jar `

**Comment by rajeshzmoke** [comment]
without the ui how can  i run the functions separately in backend?.. i need to integrate it with my project..

**Comment by erajasekar** [comment]
What's your backend language/technology? If Java, you should able to refactor this code to fit your needs. If not, we have very limited features available as a REST API. You can use it from any language/platform. Check out http://docs.innovativeastrosolutions.com/

**Comment by rajeshzmoke** [comment]
i'm using kotlin/mongodb, i mainly need the Dasha Bukthi and the planetary positions

**Comment by erajasekar** [comment]
Kotlin runs in jvm. so you should able to refactor this java code to fit your needs.
