### ISSUE TITLE
integrate java files to my android project

### ISSUE THREAD

**Issue by triosoftteam** [erajasekar/Astrosoft#17]
integrate java files to my android project

**Comment by relango** [comment]
@triosoftteam Please be specific and provide more info on what issue are you facing.

**Comment by triosoftteam** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/swing/JFrame;
        at app.astrosoft.util.AstroUtil.decimal(Unknown Source:0)
        at app.astrosoft.beans.BirthData.<init>(Unknown Source:38)
        at app.astrosoft.beans.BirthData.<init>(Unknown Source:39)
        at app.astrosoft.beans.BirthData.<init>(Unknown Source:1)

in runtime when use this functions



try {
                    Place place = new Place("Bangalore", "Karnataka", "India", 25.51, 85.47, 5.30);
                    Calendar c = new GregorianCalendar(1995, 5, 18, 5, 12, 1);
                    BirthData birthData = new BirthData("Ashwini", c, place);

                    Horoscope horoscope = new Horoscope(birthData);
                    horoscope.calculateAll();

                    System.out.println(horoscope);
                } catch (Exception e) {
                    Log.d(TAG, "onClick: " + e);
                }

**Comment by relango** [comment]
Java Swing UI doesn't work in Andriod, you can't simply take a java desktop app and run it in android. You can build UI in android yourself. You can use Astrosoft code for calculations.

**Comment by triosoftteam** [comment]
can you expain Astrosoft code how to implement code in android (java)

**Comment by relango** [comment]
@triosoftteam The code is available free. You can read the code and figure it out!.

**Comment by triosoftteam** [comment]
actually i can't get it where do i find the exact path for calculation code can you tell me the excet path to reach out
