### ISSUE TITLE
birthData is not accepting the arguments

### ISSUE THREAD

**Issue by JhaSneha** [erajasekar/Astrosoft#4]
This is the error i am facing

**Comment by erajasekar** [comment]
Which language are you coding and what build system you use? Make sure https://github.com/erajasekar/Astrosoft/blob/master/lib/swisseph.jar is in the classpath.

**Comment by JhaSneha** [comment]
I am using Kotlin and Gradle ...

**Comment by erajasekar** [comment]
Since swisseph (also few other jars in libs dir) is not available in maven central. you will need to locally install that jar as dependency in gradle.

See 
https://medium.com/@petehouston/compile-local-jar-files-with-gradle-a078e5c7a520
https://stackoverflow.com/questions/20700053/how-to-add-local-jar-file-dependency-to-build-gradle-file

Hope that helps.

Raja.

**Comment by JhaSneha** [comment]
My doubt is  if i am including your AstroSoft.jar into my project wouldn't it include the rest of external jars that you have internally added into your project

**Comment by JhaSneha** [comment]
https://github.com/JhaSneha/Astrology

**Comment by JhaSneha** [comment]
I shared my github repo link where my code is added above.
This how I am trying to invoke your function (calculateAll) from Horoscope.java, the error I  am facing  is mentioned above, currently I am using Linux Os  .
It will be a great help if u can visit to my code once and help me out with the issue.
Thank you

**Comment by erajasekar** [comment]
When you launch your app, set the jvm argument `-Djava.util.prefs.PreferencesFactory=app.astrosoft.pref.UserPreferencesFactory`.  For e.g refer to RunAstroSoft.sh

**Comment by JhaSneha** [comment]
I have added the jvm argument as you suggested above, still i am facing the issue.
Is there anything else that i need to set manually ?
Below are the errors 
018-07-25 15:30:15.730 ERROR 22167 --- [           main] app.astrosoft.pref.AstrosoftPref         : Exception in flusing preferences 

java.util.prefs.BackingStoreException: Synchronization failed for node '/app/astrosoft/pref/'
        at java.util.prefs.MacOSXPreferences.flush(MacOSXPreferences.java:230) ~[na:1.8.0_161]
        at app.astrosoft.pref.AstrosoftPref.flush(Unknown Source) [AstroSoft.jar!/:na]
        at app.astrosoft.pref.AstrosoftPref.setAstrosoftFilesDir(Unknown Source) [AstroSoft.jar!/:na]
        at app.astrosoft.pref.AstrosoftPref.setDefaults(Unknown Source) [AstroSoft.jar!/:na]
        at app.astrosoft.pref.AstrosoftPref.<init>(Unknown Source) [AstroSoft.jar!/:na]
        at app.astrosoft.ui.AstroSoft.<clinit>(Unknown Source) [AstroSoft.jar!/:na]
        at app.astrosoft.util.SwissHelper.<init>(Unknown Source) [AstroSoft.jar!/:na]
        at app.astrosoft.util.SwissHelper.<init>(Unknown Source) [AstroSoft.jar!/:na]
        at app.astrosoft.core.Horoscope.<init>(Unknown Source) [AstroSoft.jar!/:na]
        at com.example.gradle.GradleExternalJar.TestG.sample(GradleExternalJarApplication.kt:31) [classes!/:na]
        at com.example.gradle.GradleExternalJar.GradleExternalJarApplicationKt.main(GradleExternalJarApplication.kt:18) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [GradleExternalJar-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [GradleExternalJar-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [GradleExternalJar-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [GradleExternalJar-0.0.1-SNAPSHOT.jar:na]

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ExceptionInInitializerError
        at app.astrosoft.util.SwissHelper.<init>(Unknown Source)
        at app.astrosoft.util.SwissHelper.<init>(Unknown Source)
        at app.astrosoft.core.Horoscope.<init>(Unknown Source)
        at com.example.gradle.GradleExternalJar.TestG.sample(GradleExternalJarApplication.kt:31)
        at com.example.gradle.GradleExternalJar.GradleExternalJarApplicationKt.main(GradleExternalJarApplication.kt:18)
        ... 8 more
Caused by: java.awt.HeadlessException
        at sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:284)
        at app.astrosoft.ui.AstroSoft.getScreenSize(Unknown Source)
        at app.astrosoft.ui.AstroSoft.<clinit>(Unknown Source)
        ... 13 more
