### ISSUE TITLE
MenuItem New Under File menu not working.

### ISSUE THREAD

**Issue by sushiljic** [erajasekar/Astrosoft#5]
Hi, i have tried to run Astrosoft from the link [ http://sourceforge.net/projects/astrosoft/files/latest/download ]
I was able to run the program but when clicking of New MenuItem, it is showing error on console
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at app.astrosoft.ui.util.UIUtil.setPanelBackground(Unknown Source)
	at app.astrosoft.ui.dlg.AstrosoftDialog.setBackground(Unknown Source)
	at javax.swing.JDialog.dialogInit(JDialog.java:649)
	at javax.swing.JDialog.<init>(JDialog.java:279)
	at app.astrosoft.ui.dlg.AstrosoftDialog.<init>(Unknown Source)
	at app.astrosoft.ui.dlg.BirthInputDialog.<init>(Unknown Source)
	at app.astrosoft.ui.dlg.BirthInputDialog.<init>(Unknown Source)
	at app.astrosoft.ui.AstroSoft.newHoroscope(Unknown Source)
	at app.astrosoft.ui.AstrosoftAction.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.digitprop.tonic.MenuItemUI.doClick(MenuItemUI.java:1507)
	at com.digitprop.tonic.MenuItemUI$MouseInputHandler.mouseReleased(MenuItemUI.java:1294)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
^C%                                         

It seems to be Swing Error.
If would be very helpful if you can help me to fix this.
Thanks in advance :+1: 
And kudos for the awesome project

**Comment by erajasekar** [comment]
The version on source forge might be old. Can you try the version in GitHub
itself?

Thanks,
Raja.

**Comment by sushiljic** [comment]
Cool Its Working.
Let me check whether it shoot my need for not?

Anyway 
Are there any plans of changing it to some Maven projects?
